BUS/BUS/Models/Customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int C_ID { get; set; }
        public string C_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string MOBILE_NUMBER { get; set; }
        public string ADDRESS { get; set; }
    }
}

BUS/BUS/Controllers/BusesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BUS.Models;

namespace BUS.Controllers
{
    public class BusesController : Controller
    {
        private BusEasyEntities db = new BusEasyEntities();

        // GET: Buses
        public ActionResult Index()
        {
            if (Session["admin"] == null) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }
            return View(db.Buses.ToList());
        }

        // GET: Buses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bus bus = db.Buses.Find(id);
            if (bus == null)
            {
                return HttpNotFound();
            }
            return View(bus);
        }

        // GET: Buses/Create

        // GET: Customer/Create
        public ActionResult Create()
        {
            if (Session["admin"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Retrieve all routes and pass them to the view
            ViewBag.RouteList = new SelectList(db.Routes.ToList(), "ROUTE_ID", "START_LOCATION"); // Use appropriate display field
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BUS_ID,BUS_NUMBER,CAPACITY,ROUTE_ID")] Bus bus)
        {
            if (ModelState.IsValid)
            {
                db.Buses.Add(bus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // Retrieve all routes again if model state is invalid
            ViewBag.RouteList = new SelectList(db.Routes.ToList(), "ROUTE_ID", "START_LOCATION"); // Use appropriate display field
            return View(bus);
        }

        // GET: Buses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bus bus = db.Buses.Find(id);
            if (bus == null)
            {
                return HttpNotFound();
            }
            return View(bus);
        }

        // POST: Buses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BUS_ID,BUS_NUMBER,CAPACITY,ROUTE_ID")] Bus bus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bus);
        }

        // GET: Buses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bus bus = db.Buses.Find(id);
            if (bus == null)
            {
                return HttpNotFound();
            }
            return View(bus);
        }

        // POST: Buses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Bus bus = db.Buses.Find(id);
            db.Buses.Remove(bus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BUS/BUS/Controllers/RoutesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BUS.Models;

namespace BUS.Controllers
{
    public class RoutesController : Controller
    {
        private BusEasyEntities db = new BusEasyEntities();

        // GET: Routes
        public ActionResult Index()
        {

            if (Session["admin"] == null) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }
            return View(db.Routes.ToList());
        }

        // GET: Routes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.Routes.Find(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }

        // GET: Routes/Create
        public ActionResult Create()
        {

            if (Session["admin"] == null) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }
            return View();
        }

        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ROUTE_ID,START_LOCATION,END_LOCATION,DISTANCE")] Route route)
        {
            if (Session["admin"] == null) { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }
            if (ModelState.IsValid)
            {
                db.Routes.Add(route);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(route);
        }

        // GET: Routes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.Routes.Find(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ROUTE_ID,START_LOCATION,END_LOCATION,DISTANCE")] Route route)
        {
            if (ModelState.IsValid)
            {
                db.Entry(route).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(route);
        }

        // GET: Routes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Route route = db.Routes.Find(id);
            if (route == null)
            {
                return HttpNotFound();
            }
            return View(route);
        }

        // POST: Routes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Route route = db.Routes.Find(id);
            db.Routes.Remove(route);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BUS/BUS/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BUS.Models;

namespace BUS.Controllers
{
    public class TicketsController : Controller
    {
        private BusEasyEntities db = new BusEasyEntities();

        // GET: Tickets
        public ActionResult Index()
        {
            return View(db.Tickets.ToList());
        }
        public ActionResult BookingHistory()
        {
            if(Session["Id"]==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int id = Convert.ToInt32(Session["Id"]);
            return View(db.Tickets.Where(c => c.C_ID ==id).ToList());
        }

        // GET: Tickets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }
       
        // GET: Tickets/Create
        public ActionResult Create()
        {
           // if (Session["Ticket"] != null)
            //{

           // }

            // Retrieve all buses and pass them to the view
            ViewBag.BusList = new SelectList(db.Buses.ToList(), "BUS_ID", "BUS_NUMBER"); // Use appropriate display field
            return View();
        }

        // POST: Tickets/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TICKET_ID,C_ID,BUS_ID,SEAT_NUMBER,JOURNEY_DATE,PRICE")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                Session["date"]=ticket.JOURNEY_DATE;
                // Set customer ID from session
                ticket.C_ID = Convert.ToInt32(Session["Id"]);
                ticket.PRICE = 50;
                db.Tickets.Add(ticket);
                db.SaveChanges();
                Session["Ticket_id"] = ticket.TICKET_ID;
                var id =  db.Tickets.Where(c => c.C_ID == ticket.C_ID && c.BUS_ID == ticket.BUS_ID && c.SEAT_NUMBER == ticket.SEAT_NUMBER).Select(c => c.TICKET_ID);

                return RedirectToAction("Create","Payments");
            }

            // Retrieve all buses again if model state is invalid
            ViewBag.BusList = new SelectList(db.Buses.ToList(), "BUS_ID", "BUS_NUMBER"); // Use appropriate display field
            return View(ticket);
        }

        // GET: Tickets/GetBusCapacity
        public JsonResult GetBusCapacity(int busId)
        {
            var bus = db.Buses.SingleOrDefault(b => b.BUS_ID == busId);
            if (bus == null)
            {
                return Json(new { capacity = 0 }, JsonRequestBehavior.AllowGet);
            }

            var route = db.Routes.SingleOrDefault(r => r.ROUTE_ID == bus.ROUTE_ID);
            var takenSeats = db.Tickets.Where(t => t.BUS_ID == busId).Select(t => t.SEAT_NUMBER).ToList();

            return Json(new
            {
                capacity = bus.CAPACITY,
                startLocation = route?.START_LOCATION,
                endLocation = route?.END_LOCATION,
                takenSeats = takenSeats
            }, JsonRequestBehavior.AllowGet);
        }
        // GET: Tickets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TICKET_ID,C_ID,BUS_ID,SEAT_NUMBER,JOURNEY_DATE,PRICE")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ticket).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ticket);
        }

        // GET: Tickets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ticket ticket = db.Tickets.Find(id);
            db.Tickets.Remove(ticket);
            db.SaveChanges();
            if (Session["p"].Equals("1"))
            {
                return RedirectToAction("BookingHistory");
            }

            return RedirectToAction("Index");
        }
        

       



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        public ActionResult ViewTicketPDF(int id)
        {
            // Set the ticket ID in ViewBag
            ViewBag.TicketId = id;

            // Return the view
            return View();
        }


        // Action to allow the user to download the PDF
        public ActionResult DownloadTicketPDF()
        {
            // Path to the static PDF file
            string filePath = Server.MapPath("~/Content/TicketDocuments/YourTicket.pdf");
            // Name of the file that will be shown to the user during download
            string fileName = "YourTicket.pdf";

            // Return the file to the user with the specified file name
            return File(filePath, "application/pdf", fileName);
        }





    }
}

BUS/BUS/Views/Shared/Admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        .navbar {
            background-color: white;
            color: #000;
            border: none;
            box-shadow: rgba(0, 0, 0, 0.1) 0px 2px 20px;
        }

        .navbar-nav > li {
            position: relative;
            list-style: none; /* Remove default list style */
            margin: 10px 0;
        }


            .navbar-nav > li::before {
                content: '';
                position: absolute;
                bottom: 0;
                left: 0;
                width: 0;
                height: 2px; /* Height of the line */
                background-color: #007bff; /* Color of the line */
                transition: width 0.3s ease; /* Transition for width */
            }

            .navbar-nav > li:hover::before {
                width: 100%; /* Width of the line on hover */
            }

        .navbar-default .navbar-nav > li > a {
            color: black !important;
        }

        .navbar-default .navbar-nav > li.active > a {
            color: red !important; /* Set active item color to red */
            background-color: transparent !important;
        }

        .navbar-default .navbar-nav > li > a:hover,
        .navbar-default .navbar-nav > li > a:focus {
            color: red !important; /* Set hover item color to red */
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-default">
        <div class="container">
            <a href="@Url.Action("Index", "Buses")" class="navbar-brand">
                <img src="@Url.Content("~/Image/1.png")" alt="Application Logo" style="height: 40px;" />
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="nav navbar-nav me-auto">
             
                    <li>@Html.ActionLink("All Bus", "Index", "Buses", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Add Schedule", "Index", "Schedules", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("All Customers", "Index", "Customers", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("All Routes", "Index", "Routes", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("All Bookings", "Index", "Tickets", new { area = "" }, new { @class = "nav-link" })</li>
                    
                    <li>@Html.ActionLink("Payment History", "Index", "Payments", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
                <ul class="nav navbar-nav ms-auto">
                    <li>@Html.ActionLink("Logout", "AdminLogout", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>
            </div>
        </div>
    </nav>
   
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BUS/BUS/Views/Shared/Customer.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
         .navbar {
     background-color: white;
     color: #000;
     border: none;
     box-shadow: rgba(0, 0, 0, 0.1) 0px 2px 20px;
 }

 .navbar-nav > li {
     position: relative;
     list-style: none; /* Remove default list style */
     margin: 10px 0;
 }

     .navbar-nav > li::before {
         content: '';
         position: absolute;
         bottom: 0;
         left: 0;
         width: 0;
         height: 2px; /* Height of the line */
         background-color: #007bff; /* Color of the line */
         transition: width 0.3s ease; /* Transition for width */
     }

     .navbar-nav > li:hover::before {
         width: 100%; /* Width of the line on hover */
     }

 .navbar-default .navbar-nav > li > a {
     color: black !important;
 }

 .navbar-default .navbar-nav > li.active > a {
     color: red !important; /* Set active item color to red */
     background-color: transparent !important;
 }

 .navbar-default .navbar-nav > li > a:hover,
 .navbar-default .navbar-nav > li > a:focus {
     color: red !important; /* Set hover item color to red */
 }




    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-default">
        <div class="container">
            <a href="@Url.Action("Create", "Tickets")" class="navbar-brand">
                <img src="@Url.Content("~/Image/1.png")" alt="Application Logo" style="height: 40px;" />
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="nav navbar-nav me-auto">
                   
                    <li>@Html.ActionLink("Customer Profile", "Details", "Customers", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Ticket Booking", "Create", "Tickets", new { area = "" }, new { @class = "nav-link" })</li>

                    <li>@Html.ActionLink("Booking History", "BookingHistory", "Tickets", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>
                <ul class="nav navbar-nav ms-auto">
                    <li>@Html.ActionLink("Logout", "Logout", "Customers", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BUS/BUS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title BookEasy </title>
    <link src="https://cdnjs.cloudflare.com/ajax/libs/ionicons/7.4.0/collection/components/icon/icon.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        .navbar {
            background-color: white;
            color: #000;
            border: none;
            box-shadow: rgba(0, 0, 0, 0.1) 0px 2px 20px;
        }

        .navbar-nav > li {
            position: relative;
            list-style: none; /* Remove default list style */
            margin: 10px 0;
        }

            .navbar-nav > li::before {
                content: '';
                position: absolute;
                bottom: 0;
                left: 0;
                width: 0;
                height: 2px; /* Height of the line */
                background-color: #007bff; /* Color of the line */
                transition: width 0.3s ease; /* Transition for width */
            }

            .navbar-nav > li:hover::before {
                width: 100%; /* Width of the line on hover */
            }

        .navbar-default .navbar-nav > li > a {
            color: black !important;
        }

        .navbar-default .navbar-nav > li.active > a {
            color: red !important; /* Set active item color to red */
            background-color: transparent !important;
        }

        .navbar-default .navbar-nav > li > a:hover,
        .navbar-default .navbar-nav > li > a:focus {
            color: red !important; /* Set hover item color to red */
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-default">
        <div class="container">
            <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                <img src="@Url.Content("~/Image/1.png")" alt="Application Logo" style="height: 40px;" />
            </a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarNav" title="Toggle navigation" aria-controls="navbarNav"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="nav navbar-nav me-auto">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
                <ul class="nav navbar-nav ms-auto">
                    <li class="nav-item" style="border-radius: 20px;">
                        @Html.ActionLink("Register", "Create", "Customers", new { area = "" }, new { @class = "nav-link btn btn-success" })
                    </li>

                    <li class="nav-item">@Html.ActionLink("Login", "Login", "Customers", new { area = "" }, new { @class = "nav-link" })</li>
                   
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>